# Generated by Django 4.0 on 2023-05-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='buyer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
